// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: geo_api/geo.proto

package geo_api

import (
	_ "github.com/FOMBUS1/GeoTimeTracker/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Longtitude     float32                `protobuf:"fixed32,2,opt,name=longtitude,proto3" json:"longtitude,omitempty"`
	Latitude       float32                `protobuf:"fixed32,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Departure      bool                   `protobuf:"varint,4,opt,name=departure,proto3" json:"departure,omitempty"`
	CustomLocation *string                `protobuf:"bytes,5,opt,name=customLocation,proto3,oneof" json:"customLocation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocationRequest) Reset() {
	*x = LocationRequest{}
	mi := &file_geo_api_geo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationRequest) ProtoMessage() {}

func (x *LocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geo_api_geo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationRequest.ProtoReflect.Descriptor instead.
func (*LocationRequest) Descriptor() ([]byte, []int) {
	return file_geo_api_geo_proto_rawDescGZIP(), []int{0}
}

func (x *LocationRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *LocationRequest) GetLongtitude() float32 {
	if x != nil {
		return x.Longtitude
	}
	return 0
}

func (x *LocationRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationRequest) GetDeparture() bool {
	if x != nil {
		return x.Departure
	}
	return false
}

func (x *LocationRequest) GetCustomLocation() string {
	if x != nil && x.CustomLocation != nil {
		return *x.CustomLocation
	}
	return ""
}

type LocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationResponse) Reset() {
	*x = LocationResponse{}
	mi := &file_geo_api_geo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationResponse) ProtoMessage() {}

func (x *LocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geo_api_geo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationResponse.ProtoReflect.Descriptor instead.
func (*LocationResponse) Descriptor() ([]byte, []int) {
	return file_geo_api_geo_proto_rawDescGZIP(), []int{1}
}

func (x *LocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_geo_api_geo_proto protoreflect.FileDescriptor

const file_geo_api_geo_proto_rawDesc = "" +
	"\n" +
	"\x11geo_api/geo.proto\x12\x0egeo.service.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16models/geo_model.proto\x1a\x1cgoogle/api/annotations.proto\"\xca\x01\n" +
	"\x0fLocationRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1e\n" +
	"\n" +
	"longtitude\x18\x02 \x01(\x02R\n" +
	"longtitude\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tdeparture\x18\x04 \x01(\bR\tdeparture\x12+\n" +
	"\x0ecustomLocation\x18\x05 \x01(\tH\x00R\x0ecustomLocation\x88\x01\x01B\x11\n" +
	"\x0f_customLocation\",\n" +
	"\x10LocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2y\n" +
	"\n" +
	"GeoService\x12k\n" +
	"\vGetLocation\x12\x1f.geo.service.v1.LocationRequest\x1a .geo.service.v1.LocationResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/location/sendB1Z/github.com/FOMBUS1/students/internal/pb/geo_apib\x06proto3"

var (
	file_geo_api_geo_proto_rawDescOnce sync.Once
	file_geo_api_geo_proto_rawDescData []byte
)

func file_geo_api_geo_proto_rawDescGZIP() []byte {
	file_geo_api_geo_proto_rawDescOnce.Do(func() {
		file_geo_api_geo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geo_api_geo_proto_rawDesc), len(file_geo_api_geo_proto_rawDesc)))
	})
	return file_geo_api_geo_proto_rawDescData
}

var file_geo_api_geo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_geo_api_geo_proto_goTypes = []any{
	(*LocationRequest)(nil),  // 0: geo.service.v1.LocationRequest
	(*LocationResponse)(nil), // 1: geo.service.v1.LocationResponse
}
var file_geo_api_geo_proto_depIdxs = []int32{
	0, // 0: geo.service.v1.GeoService.GetLocation:input_type -> geo.service.v1.LocationRequest
	1, // 1: geo.service.v1.GeoService.GetLocation:output_type -> geo.service.v1.LocationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_geo_api_geo_proto_init() }
func file_geo_api_geo_proto_init() {
	if File_geo_api_geo_proto != nil {
		return
	}
	file_geo_api_geo_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geo_api_geo_proto_rawDesc), len(file_geo_api_geo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geo_api_geo_proto_goTypes,
		DependencyIndexes: file_geo_api_geo_proto_depIdxs,
		MessageInfos:      file_geo_api_geo_proto_msgTypes,
	}.Build()
	File_geo_api_geo_proto = out.File
	file_geo_api_geo_proto_goTypes = nil
	file_geo_api_geo_proto_depIdxs = nil
}
