// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: models/geo_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeoModel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Departure       bool                   `protobuf:"varint,2,opt,name=departure,proto3" json:"departure,omitempty"`
	LocationAddress string                 `protobuf:"bytes,3,opt,name=locationAddress,proto3" json:"locationAddress,omitempty"`
	Location        *string                `protobuf:"bytes,4,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Time            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GeoModel) Reset() {
	*x = GeoModel{}
	mi := &file_models_geo_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoModel) ProtoMessage() {}

func (x *GeoModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_geo_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoModel.ProtoReflect.Descriptor instead.
func (*GeoModel) Descriptor() ([]byte, []int) {
	return file_models_geo_model_proto_rawDescGZIP(), []int{0}
}

func (x *GeoModel) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GeoModel) GetDeparture() bool {
	if x != nil {
		return x.Departure
	}
	return false
}

func (x *GeoModel) GetLocationAddress() string {
	if x != nil {
		return x.LocationAddress
	}
	return ""
}

func (x *GeoModel) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *GeoModel) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_models_geo_model_proto protoreflect.FileDescriptor

const file_models_geo_model_proto_rawDesc = "" +
	"\n" +
	"\x16models/geo_model.proto\x12\rgeo.models.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x01\n" +
	"\bGeoModel\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1c\n" +
	"\tdeparture\x18\x02 \x01(\bR\tdeparture\x12(\n" +
	"\x0flocationAddress\x18\x03 \x01(\tR\x0flocationAddress\x12\x1f\n" +
	"\blocation\x18\x04 \x01(\tH\x00R\blocation\x88\x01\x01\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04timeB\v\n" +
	"\t_locationB6Z4github.com/FOMBUS1/GeoTimeTracker/internal/pb/modelsb\x06proto3"

var (
	file_models_geo_model_proto_rawDescOnce sync.Once
	file_models_geo_model_proto_rawDescData []byte
)

func file_models_geo_model_proto_rawDescGZIP() []byte {
	file_models_geo_model_proto_rawDescOnce.Do(func() {
		file_models_geo_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_geo_model_proto_rawDesc), len(file_models_geo_model_proto_rawDesc)))
	})
	return file_models_geo_model_proto_rawDescData
}

var file_models_geo_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_geo_model_proto_goTypes = []any{
	(*GeoModel)(nil),              // 0: geo.models.v1.GeoModel
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_models_geo_model_proto_depIdxs = []int32{
	1, // 0: geo.models.v1.GeoModel.time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_geo_model_proto_init() }
func file_models_geo_model_proto_init() {
	if File_models_geo_model_proto != nil {
		return
	}
	file_models_geo_model_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_geo_model_proto_rawDesc), len(file_models_geo_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_geo_model_proto_goTypes,
		DependencyIndexes: file_models_geo_model_proto_depIdxs,
		MessageInfos:      file_models_geo_model_proto_msgTypes,
	}.Build()
	File_models_geo_model_proto = out.File
	file_models_geo_model_proto_goTypes = nil
	file_models_geo_model_proto_depIdxs = nil
}
