// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: geo_stats_api/geo_stats.proto

package geo_stats_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeoStatsService_GetLocationStats_FullMethodName = "/geo_stats.service.v1.GeoStatsService/GetLocationStats"
	GeoStatsService_GetTopTimeSpent_FullMethodName  = "/geo_stats.service.v1.GeoStatsService/GetTopTimeSpent"
)

// GeoStatsServiceClient is the client API for GeoStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeoStatsServiceClient interface {
	// Получаем информацию о потраченном времени в конкретном месте за период
	GetLocationStats(ctx context.Context, in *UserLocationRequests, opts ...grpc.CallOption) (*TimeSpentResponses, error)
	// Получаем топ мест за период
	GetTopTimeSpent(ctx context.Context, in *TimePeriodRequests, opts ...grpc.CallOption) (*TimeSpentResponses, error)
}

type geoStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoStatsServiceClient(cc grpc.ClientConnInterface) GeoStatsServiceClient {
	return &geoStatsServiceClient{cc}
}

func (c *geoStatsServiceClient) GetLocationStats(ctx context.Context, in *UserLocationRequests, opts ...grpc.CallOption) (*TimeSpentResponses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeSpentResponses)
	err := c.cc.Invoke(ctx, GeoStatsService_GetLocationStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoStatsServiceClient) GetTopTimeSpent(ctx context.Context, in *TimePeriodRequests, opts ...grpc.CallOption) (*TimeSpentResponses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeSpentResponses)
	err := c.cc.Invoke(ctx, GeoStatsService_GetTopTimeSpent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoStatsServiceServer is the server API for GeoStatsService service.
// All implementations must embed UnimplementedGeoStatsServiceServer
// for forward compatibility.
type GeoStatsServiceServer interface {
	// Получаем информацию о потраченном времени в конкретном месте за период
	GetLocationStats(context.Context, *UserLocationRequests) (*TimeSpentResponses, error)
	// Получаем топ мест за период
	GetTopTimeSpent(context.Context, *TimePeriodRequests) (*TimeSpentResponses, error)
	mustEmbedUnimplementedGeoStatsServiceServer()
}

// UnimplementedGeoStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeoStatsServiceServer struct{}

func (UnimplementedGeoStatsServiceServer) GetLocationStats(context.Context, *UserLocationRequests) (*TimeSpentResponses, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLocationStats not implemented")
}
func (UnimplementedGeoStatsServiceServer) GetTopTimeSpent(context.Context, *TimePeriodRequests) (*TimeSpentResponses, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopTimeSpent not implemented")
}
func (UnimplementedGeoStatsServiceServer) mustEmbedUnimplementedGeoStatsServiceServer() {}
func (UnimplementedGeoStatsServiceServer) testEmbeddedByValue()                         {}

// UnsafeGeoStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoStatsServiceServer will
// result in compilation errors.
type UnsafeGeoStatsServiceServer interface {
	mustEmbedUnimplementedGeoStatsServiceServer()
}

func RegisterGeoStatsServiceServer(s grpc.ServiceRegistrar, srv GeoStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedGeoStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeoStatsService_ServiceDesc, srv)
}

func _GeoStatsService_GetLocationStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLocationRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoStatsServiceServer).GetLocationStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoStatsService_GetLocationStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoStatsServiceServer).GetLocationStats(ctx, req.(*UserLocationRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoStatsService_GetTopTimeSpent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimePeriodRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoStatsServiceServer).GetTopTimeSpent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoStatsService_GetTopTimeSpent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoStatsServiceServer).GetTopTimeSpent(ctx, req.(*TimePeriodRequests))
	}
	return interceptor(ctx, in, info, handler)
}

// GeoStatsService_ServiceDesc is the grpc.ServiceDesc for GeoStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geo_stats.service.v1.GeoStatsService",
	HandlerType: (*GeoStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLocationStats",
			Handler:    _GeoStatsService_GetLocationStats_Handler,
		},
		{
			MethodName: "GetTopTimeSpent",
			Handler:    _GeoStatsService_GetTopTimeSpent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geo_stats_api/geo_stats.proto",
}
