// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: geo_stats_api/geo_stats.proto

package geo_stats_api

import (
	_ "github.com/FOMBUS1/GeoTimeTracker/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Period int32

const (
	Period_LAST  Period = 0
	Period_DAY   Period = 1
	Period_WEEK  Period = 2
	Period_MONTH Period = 3
	Period_YEAR  Period = 4
)

// Enum value maps for Period.
var (
	Period_name = map[int32]string{
		0: "LAST",
		1: "DAY",
		2: "WEEK",
		3: "MONTH",
		4: "YEAR",
	}
	Period_value = map[string]int32{
		"LAST":  0,
		"DAY":   1,
		"WEEK":  2,
		"MONTH": 3,
		"YEAR":  4,
	}
)

func (x Period) Enum() *Period {
	p := new(Period)
	*p = x
	return p
}

func (x Period) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Period) Descriptor() protoreflect.EnumDescriptor {
	return file_geo_stats_api_geo_stats_proto_enumTypes[0].Descriptor()
}

func (Period) Type() protoreflect.EnumType {
	return &file_geo_stats_api_geo_stats_proto_enumTypes[0]
}

func (x Period) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Period.Descriptor instead.
func (Period) EnumDescriptor() ([]byte, []int) {
	return file_geo_stats_api_geo_stats_proto_rawDescGZIP(), []int{0}
}

type UserLocationRequests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*UserLocationRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLocationRequests) Reset() {
	*x = UserLocationRequests{}
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLocationRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLocationRequests) ProtoMessage() {}

func (x *UserLocationRequests) ProtoReflect() protoreflect.Message {
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLocationRequests.ProtoReflect.Descriptor instead.
func (*UserLocationRequests) Descriptor() ([]byte, []int) {
	return file_geo_stats_api_geo_stats_proto_rawDescGZIP(), []int{0}
}

func (x *UserLocationRequests) GetRequests() []*UserLocationRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type UserLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LocationId    uint64                 `protobuf:"varint,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Period        Period                 `protobuf:"varint,3,opt,name=period,proto3,enum=geo_stats.service.v1.Period" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLocationRequest) Reset() {
	*x = UserLocationRequest{}
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLocationRequest) ProtoMessage() {}

func (x *UserLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLocationRequest.ProtoReflect.Descriptor instead.
func (*UserLocationRequest) Descriptor() ([]byte, []int) {
	return file_geo_stats_api_geo_stats_proto_rawDescGZIP(), []int{1}
}

func (x *UserLocationRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserLocationRequest) GetLocationId() uint64 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *UserLocationRequest) GetPeriod() Period {
	if x != nil {
		return x.Period
	}
	return Period_LAST
}

type TimePeriodRequests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*TimePeriodRequest   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimePeriodRequests) Reset() {
	*x = TimePeriodRequests{}
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimePeriodRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimePeriodRequests) ProtoMessage() {}

func (x *TimePeriodRequests) ProtoReflect() protoreflect.Message {
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimePeriodRequests.ProtoReflect.Descriptor instead.
func (*TimePeriodRequests) Descriptor() ([]byte, []int) {
	return file_geo_stats_api_geo_stats_proto_rawDescGZIP(), []int{2}
}

func (x *TimePeriodRequests) GetRequests() []*TimePeriodRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type TimePeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Period        Period                 `protobuf:"varint,2,opt,name=period,proto3,enum=geo_stats.service.v1.Period" json:"period,omitempty"`
	TopK          *uint32                `protobuf:"varint,3,opt,name=top_k,json=topK,proto3,oneof" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimePeriodRequest) Reset() {
	*x = TimePeriodRequest{}
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimePeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimePeriodRequest) ProtoMessage() {}

func (x *TimePeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimePeriodRequest.ProtoReflect.Descriptor instead.
func (*TimePeriodRequest) Descriptor() ([]byte, []int) {
	return file_geo_stats_api_geo_stats_proto_rawDescGZIP(), []int{3}
}

func (x *TimePeriodRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TimePeriodRequest) GetPeriod() Period {
	if x != nil {
		return x.Period
	}
	return Period_LAST
}

func (x *TimePeriodRequest) GetTopK() uint32 {
	if x != nil && x.TopK != nil {
		return *x.TopK
	}
	return 0
}

type LocationStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    uint64                 `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	TimeSeconds   uint64                 `protobuf:"varint,2,opt,name=time_seconds,json=timeSeconds,proto3" json:"time_seconds,omitempty"`
	Period        Period                 `protobuf:"varint,3,opt,name=period,proto3,enum=geo_stats.service.v1.Period" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationStat) Reset() {
	*x = LocationStat{}
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationStat) ProtoMessage() {}

func (x *LocationStat) ProtoReflect() protoreflect.Message {
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationStat.ProtoReflect.Descriptor instead.
func (*LocationStat) Descriptor() ([]byte, []int) {
	return file_geo_stats_api_geo_stats_proto_rawDescGZIP(), []int{4}
}

func (x *LocationStat) GetLocationId() uint64 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *LocationStat) GetTimeSeconds() uint64 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *LocationStat) GetPeriod() Period {
	if x != nil {
		return x.Period
	}
	return Period_LAST
}

type TimeSpentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Stats         []*LocationStat        `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSpentResponse) Reset() {
	*x = TimeSpentResponse{}
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSpentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSpentResponse) ProtoMessage() {}

func (x *TimeSpentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSpentResponse.ProtoReflect.Descriptor instead.
func (*TimeSpentResponse) Descriptor() ([]byte, []int) {
	return file_geo_stats_api_geo_stats_proto_rawDescGZIP(), []int{5}
}

func (x *TimeSpentResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TimeSpentResponse) GetStats() []*LocationStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type TimeSpentResponses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*TimeSpentResponse   `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSpentResponses) Reset() {
	*x = TimeSpentResponses{}
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSpentResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSpentResponses) ProtoMessage() {}

func (x *TimeSpentResponses) ProtoReflect() protoreflect.Message {
	mi := &file_geo_stats_api_geo_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSpentResponses.ProtoReflect.Descriptor instead.
func (*TimeSpentResponses) Descriptor() ([]byte, []int) {
	return file_geo_stats_api_geo_stats_proto_rawDescGZIP(), []int{6}
}

func (x *TimeSpentResponses) GetResponses() []*TimeSpentResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_geo_stats_api_geo_stats_proto protoreflect.FileDescriptor

const file_geo_stats_api_geo_stats_proto_rawDesc = "" +
	"\n" +
	"\x1dgeo_stats_api/geo_stats.proto\x12\x14geo_stats.service.v1\x1a\x16models/geo_model.proto\x1a\x1cgoogle/api/annotations.proto\"]\n" +
	"\x14UserLocationRequests\x12E\n" +
	"\brequests\x18\x01 \x03(\v2).geo_stats.service.v1.UserLocationRequestR\brequests\"\x85\x01\n" +
	"\x13UserLocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\x04R\n" +
	"locationId\x124\n" +
	"\x06period\x18\x03 \x01(\x0e2\x1c.geo_stats.service.v1.PeriodR\x06period\"Y\n" +
	"\x12TimePeriodRequests\x12C\n" +
	"\brequests\x18\x01 \x03(\v2'.geo_stats.service.v1.TimePeriodRequestR\brequests\"\x86\x01\n" +
	"\x11TimePeriodRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x124\n" +
	"\x06period\x18\x02 \x01(\x0e2\x1c.geo_stats.service.v1.PeriodR\x06period\x12\x18\n" +
	"\x05top_k\x18\x03 \x01(\rH\x00R\x04topK\x88\x01\x01B\b\n" +
	"\x06_top_k\"\x88\x01\n" +
	"\fLocationStat\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x04R\n" +
	"locationId\x12!\n" +
	"\ftime_seconds\x18\x02 \x01(\x04R\vtimeSeconds\x124\n" +
	"\x06period\x18\x03 \x01(\x0e2\x1c.geo_stats.service.v1.PeriodR\x06period\"f\n" +
	"\x11TimeSpentResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x128\n" +
	"\x05stats\x18\x02 \x03(\v2\".geo_stats.service.v1.LocationStatR\x05stats\"[\n" +
	"\x12TimeSpentResponses\x12E\n" +
	"\tresponses\x18\x01 \x03(\v2'.geo_stats.service.v1.TimeSpentResponseR\tresponses*:\n" +
	"\x06Period\x12\b\n" +
	"\x04LAST\x10\x00\x12\a\n" +
	"\x03DAY\x10\x01\x12\b\n" +
	"\x04WEEK\x10\x02\x12\t\n" +
	"\x05MONTH\x10\x03\x12\b\n" +
	"\x04YEAR\x10\x042\xa4\x02\n" +
	"\x0fGeoStatsService\x12\x88\x01\n" +
	"\x10GetLocationStats\x12*.geo_stats.service.v1.UserLocationRequests\x1a(.geo_stats.service.v1.TimeSpentResponses\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/get_location_stats\x12\x85\x01\n" +
	"\x0fGetTopTimeSpent\x12(.geo_stats.service.v1.TimePeriodRequests\x1a(.geo_stats.service.v1.TimeSpentResponses\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/get_top_time_spentB=Z;github.com/FOMBUS1/GeoTimeTracker/internal/pb/geo_stats_apib\x06proto3"

var (
	file_geo_stats_api_geo_stats_proto_rawDescOnce sync.Once
	file_geo_stats_api_geo_stats_proto_rawDescData []byte
)

func file_geo_stats_api_geo_stats_proto_rawDescGZIP() []byte {
	file_geo_stats_api_geo_stats_proto_rawDescOnce.Do(func() {
		file_geo_stats_api_geo_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geo_stats_api_geo_stats_proto_rawDesc), len(file_geo_stats_api_geo_stats_proto_rawDesc)))
	})
	return file_geo_stats_api_geo_stats_proto_rawDescData
}

var file_geo_stats_api_geo_stats_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_geo_stats_api_geo_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_geo_stats_api_geo_stats_proto_goTypes = []any{
	(Period)(0),                  // 0: geo_stats.service.v1.Period
	(*UserLocationRequests)(nil), // 1: geo_stats.service.v1.UserLocationRequests
	(*UserLocationRequest)(nil),  // 2: geo_stats.service.v1.UserLocationRequest
	(*TimePeriodRequests)(nil),   // 3: geo_stats.service.v1.TimePeriodRequests
	(*TimePeriodRequest)(nil),    // 4: geo_stats.service.v1.TimePeriodRequest
	(*LocationStat)(nil),         // 5: geo_stats.service.v1.LocationStat
	(*TimeSpentResponse)(nil),    // 6: geo_stats.service.v1.TimeSpentResponse
	(*TimeSpentResponses)(nil),   // 7: geo_stats.service.v1.TimeSpentResponses
}
var file_geo_stats_api_geo_stats_proto_depIdxs = []int32{
	2, // 0: geo_stats.service.v1.UserLocationRequests.requests:type_name -> geo_stats.service.v1.UserLocationRequest
	0, // 1: geo_stats.service.v1.UserLocationRequest.period:type_name -> geo_stats.service.v1.Period
	4, // 2: geo_stats.service.v1.TimePeriodRequests.requests:type_name -> geo_stats.service.v1.TimePeriodRequest
	0, // 3: geo_stats.service.v1.TimePeriodRequest.period:type_name -> geo_stats.service.v1.Period
	0, // 4: geo_stats.service.v1.LocationStat.period:type_name -> geo_stats.service.v1.Period
	5, // 5: geo_stats.service.v1.TimeSpentResponse.stats:type_name -> geo_stats.service.v1.LocationStat
	6, // 6: geo_stats.service.v1.TimeSpentResponses.responses:type_name -> geo_stats.service.v1.TimeSpentResponse
	1, // 7: geo_stats.service.v1.GeoStatsService.GetLocationStats:input_type -> geo_stats.service.v1.UserLocationRequests
	3, // 8: geo_stats.service.v1.GeoStatsService.GetTopTimeSpent:input_type -> geo_stats.service.v1.TimePeriodRequests
	7, // 9: geo_stats.service.v1.GeoStatsService.GetLocationStats:output_type -> geo_stats.service.v1.TimeSpentResponses
	7, // 10: geo_stats.service.v1.GeoStatsService.GetTopTimeSpent:output_type -> geo_stats.service.v1.TimeSpentResponses
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_geo_stats_api_geo_stats_proto_init() }
func file_geo_stats_api_geo_stats_proto_init() {
	if File_geo_stats_api_geo_stats_proto != nil {
		return
	}
	file_geo_stats_api_geo_stats_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geo_stats_api_geo_stats_proto_rawDesc), len(file_geo_stats_api_geo_stats_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geo_stats_api_geo_stats_proto_goTypes,
		DependencyIndexes: file_geo_stats_api_geo_stats_proto_depIdxs,
		EnumInfos:         file_geo_stats_api_geo_stats_proto_enumTypes,
		MessageInfos:      file_geo_stats_api_geo_stats_proto_msgTypes,
	}.Build()
	File_geo_stats_api_geo_stats_proto = out.File
	file_geo_stats_api_geo_stats_proto_goTypes = nil
	file_geo_stats_api_geo_stats_proto_depIdxs = nil
}
