// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/FOMBUS1/GeoTimeTracker/internal/pb/geo_stats_api"
	"github.com/FOMBUS1/GeoTimeTracker/internal/pb/models"
	mock "github.com/stretchr/testify/mock"
)

// NewGeoStatsStorage creates a new instance of GeoStatsStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGeoStatsStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *GeoStatsStorage {
	mock := &GeoStatsStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GeoStatsStorage is an autogenerated mock type for the GeoStatsStorage type
type GeoStatsStorage struct {
	mock.Mock
}

type GeoStatsStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *GeoStatsStorage) EXPECT() *GeoStatsStorage_Expecter {
	return &GeoStatsStorage_Expecter{mock: &_m.Mock}
}

// GetStatsByLocations provides a mock function for the type GeoStatsStorage
func (_mock *GeoStatsStorage) GetStatsByLocations(ctx context.Context, reqs []*geo_stats_api.UserLocationRequest) ([]*geo_stats_api.TimeSpentResponse, error) {
	ret := _mock.Called(ctx, reqs)

	if len(ret) == 0 {
		panic("no return value specified for GetStatsByLocations")
	}

	var r0 []*geo_stats_api.TimeSpentResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*geo_stats_api.UserLocationRequest) ([]*geo_stats_api.TimeSpentResponse, error)); ok {
		return returnFunc(ctx, reqs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*geo_stats_api.UserLocationRequest) []*geo_stats_api.TimeSpentResponse); ok {
		r0 = returnFunc(ctx, reqs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*geo_stats_api.TimeSpentResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []*geo_stats_api.UserLocationRequest) error); ok {
		r1 = returnFunc(ctx, reqs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GeoStatsStorage_GetStatsByLocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatsByLocations'
type GeoStatsStorage_GetStatsByLocations_Call struct {
	*mock.Call
}

// GetStatsByLocations is a helper method to define mock.On call
//   - ctx context.Context
//   - reqs []*geo_stats_api.UserLocationRequest
func (_e *GeoStatsStorage_Expecter) GetStatsByLocations(ctx interface{}, reqs interface{}) *GeoStatsStorage_GetStatsByLocations_Call {
	return &GeoStatsStorage_GetStatsByLocations_Call{Call: _e.mock.On("GetStatsByLocations", ctx, reqs)}
}

func (_c *GeoStatsStorage_GetStatsByLocations_Call) Run(run func(ctx context.Context, reqs []*geo_stats_api.UserLocationRequest)) *GeoStatsStorage_GetStatsByLocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*geo_stats_api.UserLocationRequest
		if args[1] != nil {
			arg1 = args[1].([]*geo_stats_api.UserLocationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GeoStatsStorage_GetStatsByLocations_Call) Return(timeSpentResponses []*geo_stats_api.TimeSpentResponse, err error) *GeoStatsStorage_GetStatsByLocations_Call {
	_c.Call.Return(timeSpentResponses, err)
	return _c
}

func (_c *GeoStatsStorage_GetStatsByLocations_Call) RunAndReturn(run func(ctx context.Context, reqs []*geo_stats_api.UserLocationRequest) ([]*geo_stats_api.TimeSpentResponse, error)) *GeoStatsStorage_GetStatsByLocations_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopStats provides a mock function for the type GeoStatsStorage
func (_mock *GeoStatsStorage) GetTopStats(ctx context.Context, reqs []*geo_stats_api.TimePeriodRequest) ([]*geo_stats_api.TimeSpentResponse, error) {
	ret := _mock.Called(ctx, reqs)

	if len(ret) == 0 {
		panic("no return value specified for GetTopStats")
	}

	var r0 []*geo_stats_api.TimeSpentResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*geo_stats_api.TimePeriodRequest) ([]*geo_stats_api.TimeSpentResponse, error)); ok {
		return returnFunc(ctx, reqs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*geo_stats_api.TimePeriodRequest) []*geo_stats_api.TimeSpentResponse); ok {
		r0 = returnFunc(ctx, reqs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*geo_stats_api.TimeSpentResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []*geo_stats_api.TimePeriodRequest) error); ok {
		r1 = returnFunc(ctx, reqs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GeoStatsStorage_GetTopStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopStats'
type GeoStatsStorage_GetTopStats_Call struct {
	*mock.Call
}

// GetTopStats is a helper method to define mock.On call
//   - ctx context.Context
//   - reqs []*geo_stats_api.TimePeriodRequest
func (_e *GeoStatsStorage_Expecter) GetTopStats(ctx interface{}, reqs interface{}) *GeoStatsStorage_GetTopStats_Call {
	return &GeoStatsStorage_GetTopStats_Call{Call: _e.mock.On("GetTopStats", ctx, reqs)}
}

func (_c *GeoStatsStorage_GetTopStats_Call) Run(run func(ctx context.Context, reqs []*geo_stats_api.TimePeriodRequest)) *GeoStatsStorage_GetTopStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*geo_stats_api.TimePeriodRequest
		if args[1] != nil {
			arg1 = args[1].([]*geo_stats_api.TimePeriodRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GeoStatsStorage_GetTopStats_Call) Return(timeSpentResponses []*geo_stats_api.TimeSpentResponse, err error) *GeoStatsStorage_GetTopStats_Call {
	_c.Call.Return(timeSpentResponses, err)
	return _c
}

func (_c *GeoStatsStorage_GetTopStats_Call) RunAndReturn(run func(ctx context.Context, reqs []*geo_stats_api.TimePeriodRequest) ([]*geo_stats_api.TimeSpentResponse, error)) *GeoStatsStorage_GetTopStats_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUserVisits provides a mock function for the type GeoStatsStorage
func (_mock *GeoStatsStorage) UpsertUserVisits(ctx context.Context, userVisits []*models.GeoKafkaMessage) error {
	ret := _mock.Called(ctx, userVisits)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserVisits")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.GeoKafkaMessage) error); ok {
		r0 = returnFunc(ctx, userVisits)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GeoStatsStorage_UpsertUserVisits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserVisits'
type GeoStatsStorage_UpsertUserVisits_Call struct {
	*mock.Call
}

// UpsertUserVisits is a helper method to define mock.On call
//   - ctx context.Context
//   - userVisits []*models.GeoKafkaMessage
func (_e *GeoStatsStorage_Expecter) UpsertUserVisits(ctx interface{}, userVisits interface{}) *GeoStatsStorage_UpsertUserVisits_Call {
	return &GeoStatsStorage_UpsertUserVisits_Call{Call: _e.mock.On("UpsertUserVisits", ctx, userVisits)}
}

func (_c *GeoStatsStorage_UpsertUserVisits_Call) Run(run func(ctx context.Context, userVisits []*models.GeoKafkaMessage)) *GeoStatsStorage_UpsertUserVisits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.GeoKafkaMessage
		if args[1] != nil {
			arg1 = args[1].([]*models.GeoKafkaMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GeoStatsStorage_UpsertUserVisits_Call) Return(err error) *GeoStatsStorage_UpsertUserVisits_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GeoStatsStorage_UpsertUserVisits_Call) RunAndReturn(run func(ctx context.Context, userVisits []*models.GeoKafkaMessage) error) *GeoStatsStorage_UpsertUserVisits_Call {
	_c.Call.Return(run)
	return _c
}
